### PR TITLE
fix(pom): Running "mvn site" results in error with message "Could not…

### PR DESCRIPTION
**Pull request by joquijada**
… connect to Central search"

Applied the fix described here: https://github.com/jeremylong/DependencyCheck/issues/978

#8

## Description of change

In the pom.xml, upgraded dependency-check-maven from 3.0.1 to 3.0.2, to pick up critical fix described [here](https://github.com/jeremylong/DependencyCheck/issues/978).

### CODE REVIEW

**Comment by gregswindle** [comment]
Thanks very much, @joquijada, this is great!

@vladrazin could you please work with @joquijada to ensure your needs are met with dependencies and goals added to this `pom.xml`?

**Comment by gregswindle** [comment]
@joquijada @vladrazin 

I'm unable to clone this repository from work, so I cannot review this PR immediately. I'll keep you posted. 😠

**Review by gregswindle — APPROVED** [review]
LGTM! Thanks very much, Jose.

**Comment by joquijada** [comment]
I have deleted the branch, thanks all! Glad to be able to help.

**Pull request merged**
